### ISSUE TITLE
Mention CID alternative 

### ISSUE THREAD

**Issue by niftylettuce** [mixmaxhq/nodemailer-plugin-inline-base64#5]
New alternative: https://github.com/crocodilejs/nodemailer-base64-to-s3

CID is super buggy, especially depending on transport service.

So I crafted this package that uploads images to S3/CloudFront with absolute URL's.

This is way more accurate than using broken CID support!

Maybe you could mention it at the top of your Readme?  If I had known this existed I would have loved to save time and use it right away instead of this, which caused such a big headache.

Thanks ❤️

**Comment by bradvogel** [comment]
Awesome! Added to top here https://github.com/mixmaxhq/nodemailer-plugin-inline-base64/pull/6 and distinguished between the online/offline use case.
